### PR TITLE
docs: update conda install pyscf

### PR DESCRIPTION
**Pull request by LePingKYXK**
update the installation of the PySCF. It can be directly installed by using `conda install -c conda-forge pyscf`.

### CODE REVIEW

**Comment by y1xiaoc** [comment]
That's quite interesting. It seems that on pyscf's official website the pip way is still the recommend method. I wonder who is maintaining this conda-forge version?

**Comment by LePingKYXK** [comment]
> That's quite interesting. It seems that on pyscf's official website the pip way is still the recommend method. I wonder who is maintaining this conda-forge version?

I do not know the maintainer. But the official site of PySCF also provides the `conda install` option (`conda install -c pyscf pyscf`). Indeed, the extensions are not available through `conda install`. That's why `pip install` is recommended.

**Comment by y1xiaoc** [comment]
Sorry for the late reply. I guess we may follow the pyscf recommendation for the time being. So how about stay with pip for pyscf unless they make any new changes or a new version?

**Comment by LePingKYXK** [comment]
> Sorry for the late reply. I guess we may follow the pyscf recommendation for the time being. So how about stay with pip for pyscf unless they make any new changes or a new version?


Sure. I agree to keep the current instructions until the PySCF website updated.

**Pull request closed without merging**
